---
# tasks file for swaptrasher
- block:
    - name: disable swapfile
      shell: swapoff -a {{ path_swap }}swapfile
      when: ansible_facts.swapfree_mb > 0
    - name: remove swapfile
      file:
        path: "{{ path_swap }}swapfile"
        state: absent
      when: ansible_facts.swapfree_mb > 0
    - name: removing swapline in fstab
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^{{ path_swap }}swapfile'
        state: absent
      when: ansible_facts.swapfree_mb > 0
